version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - "discovery.type=single-node"
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    ports:
      - 5601:5601

  fluentd:
    image: my-fluentd
    volumes:
      - ./:/fluentd/etc/
    ports:
      - 24224:24224
      - 24224:24224/udp
    depends_on:
      - elasticsearch
    environment:
      - FLUENTD_CONF=fluent-efk.conf

  api:
    image: my-app-log
    ports:
      - 8080:8080
    depends_on:
      - fluentd
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: "api.{{.ImageName}}"
        fluentd-async: "true"
